### PR TITLE
Reputation fixes

### PR DESCRIPTION
**Pull request by therahedwig**
Touches upon some of the reputation stuff in #38 

I spend a lot of time on sciencing for the [reputation wiki page](https://dwarffortresswiki.org/index.php/DF2014:Reputation), so I had to change 'lover' to 'bonded', and I know there's still a good chunk of reps missing.

For .47 I have gotten preaching and flatterer rep too, so we'll need to add that later.

One caveat with this pull; I haven't done anything java related for over a decade, so I didn't know how to 'build' and test the code.

### CODE REVIEW

**Comment by therahedwig** [comment]
Ok, I checked and this builds and works as advertised.

But, the relationship stuff is far more complex than the current code allows for...

**Comment by McArcady** [comment]
easiest way I found to build and test the code:
`$ mvn package && java -jar target/legendsbrowser-1.17.2-shaded.jar  -w legends.xml`

**Comment by therahedwig** [comment]
> easiest way I found to build and test the code:
> `$ mvn package && java -jar target/legendsbrowser-1.17.2-shaded.jar -w legends.xml`

Thanks! I managed to get it to build already, but I think we should add this to the readme so that it'll be easier for newbies to contribute...

**Comment by robertjanetzko** [comment]
> easiest way I found to build and test the code:
> `$ mvn package && java -jar target/legendsbrowser-1.17.2-shaded.jar -w legends.xml`

you can just download eclipse (from eclipse.org) and import the project as maven project and run it in debug mode with hot-code-swap from there. should be a lot easier than builing the whole project every time.

**Comment by therahedwig** [comment]
Yeah, I ended up going with eclipse in the end. I've tweaked the relationship profile list stuff as much as I could. I do feel there's a lot of duplication between the entity rep and the relationship profile right now, but not sure what to do here to reduce that. The reps now get listed, as well as the general attitude towards a person.

Other than that, the historical and identity relationship profiles get added to the visual one. There's still the marker for both relationship_profile_hf_visual and relationship_profile_hf_identity where they indicate which identities they know, but I am unsure what this value points at atm.

**Pull request merged**
