### PR TITLE
Fix names of HF positions with static positions by race

### PR DESCRIPTION
**Pull request by McArcady**
The names of positions (king, law-maker, druid, ...) are not provided anymore by events "create entity position".
I replaced them by their static default names for each race (except necromancers).

### CODE REVIEW

**Comment by therahedwig** [comment]
I thought the human and goblin positions get generated now? meaning these names are not the only ones...

**Comment by McArcady** [comment]
Oh thanks, I overlooked that part.
That explains the similarities between positions of goblins and humans in my world export.
I propose we keep the positions for dwarves and elves (initially defined in the raws, but not available in the xml), and reduce positions for other races to 'law-giver' and 'master'.

**Comment by therahedwig** [comment]
If they used to be provided, maybe we should make a bugreport on the df mantis that it is now impossible to tell what kind of position changes took place?

**Comment by McArcady** [comment]
Ok I removed all static names for positions of goblins and humans that are now generated by the game.

**Pull request merged**
